// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEnv4iXC2ft9s9mQMgNGkklg99tp1A6J8',
    appId: '1:1064813346164:web:226fef4e0b3676fb168021',
    messagingSenderId: '1064813346164',
    projectId: 'bridgelingo-2a5c5',
    authDomain: 'bridgelingo-2a5c5.firebaseapp.com',
    storageBucket: 'bridgelingo-2a5c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANMOElCNOQ9FpJT9QSopTAsYQlKBjc14Y',
    appId: '1:1064813346164:android:596e09f23e8cc7e9168021',
    messagingSenderId: '1064813346164',
    projectId: 'bridgelingo-2a5c5',
    storageBucket: 'bridgelingo-2a5c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQT8pwRyRjCO-ANRSF5sPW4thrpepLFFg',
    appId: '1:1064813346164:ios:28146cf6f9903fca168021',
    messagingSenderId: '1064813346164',
    projectId: 'bridgelingo-2a5c5',
    storageBucket: 'bridgelingo-2a5c5.firebasestorage.app',
    iosClientId: '1064813346164-keblhod8topjsga6ppr6rm2hfmr02ufb.apps.googleusercontent.com',
    iosBundleId: 'com.example.bridgelingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQT8pwRyRjCO-ANRSF5sPW4thrpepLFFg',
    appId: '1:1064813346164:ios:28146cf6f9903fca168021',
    messagingSenderId: '1064813346164',
    projectId: 'bridgelingo-2a5c5',
    storageBucket: 'bridgelingo-2a5c5.firebasestorage.app',
    iosClientId: '1064813346164-keblhod8topjsga6ppr6rm2hfmr02ufb.apps.googleusercontent.com',
    iosBundleId: 'com.example.bridgelingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEnv4iXC2ft9s9mQMgNGkklg99tp1A6J8',
    appId: '1:1064813346164:web:04ad1234af83507f168021',
    messagingSenderId: '1064813346164',
    projectId: 'bridgelingo-2a5c5',
    authDomain: 'bridgelingo-2a5c5.firebaseapp.com',
    storageBucket: 'bridgelingo-2a5c5.firebasestorage.app',
  );
}
